# Generated by Django 3.2.7 on 2025-05-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField()),
                ('image', models.ImageField(upload_to='project2_images/')),
            ],
        ),
    ]
