# Generated by Django 3.2.7 on 2025-05-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projecttwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_link', models.URLField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('category', models.CharField(choices=[('odoo', 'Odoo'), ('django', 'Django'), ('python', 'Python'), ('javascript', 'JavaScript'), ('bootstrap', 'Bootstrap')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectTwo',
        ),
    ]
