# Generated by Django 3.2.7 on 2025-06-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20250519_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('odoo', 'Odoo'), ('javascript', 'JavaScript'), ('bootstrap', 'Bootstrap'), ('dataengineering', 'Data Engineering'), ('webdevelopment', 'Web Development'), ('ml', 'Machine Learning')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='home.Category'),
        ),
    ]
