# Generated by Django 3.2.7 on 2025-06-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20250604_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='categories',
        ),
    ]
